# The west manifest file for the Zephyr EC FW.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#

west:
  url: https://github.com/zephyrproject-rtos/west
  version: v0.7.2

manifest:

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # The list of dependencies
  #
  projects:
    # Open source branch uses official Zephyr tree
    - name: zephyr_public
      repo-path: zephyr.git
      path: ecfwwork/zephyr_fork
      remote: zephyrproject
      revision: v4.4.0
      west-commands: scripts/west-commands.yml

    - name: cmsis
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
      path: ecfwwork/modules/hal/cmsis
      remote: zephyrproject

    - name: cmsis_6
      repo-path: CMSIS_6
      revision: 30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74
      path: ecfwwork/modules/hal/cmsis_6
      remote: zephyrproject
      groups:
        - hal



    - name: hal_microchip
      revision: 86f3ea6b389d860332bd81ae8b97543def619395
      path: ecfwwork/modules/hal/microchip
      groups:
        - hal
      remote: zephyrproject
    - name: picolibc
      path: ecfwwork/modules/lib/picolibc
      revision: 01254932e8e81085817ed61fd858648584ffe37c
      remote: zephyrproject
  self:
    path: ecfwwork
