# The west manifest file for the Zephyr EC FW.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#

west:
  url: https://github.com/zephyrproject-rtos/west
  version: v0.7.2

manifest:
  defaults:
    remote: wss

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: wss
      url-base: https://gitlab.devtools.intel.com/wss-pse-io-and-power-delivery
    - name: wss_tools
      url-base: https://gitlab.devtools.intel.com/wss-pse-io-and-power-delivery-tools

  # The list of dependencies
  #
  projects:
    # Open source branch uses official Zephyr tree
    - name: zephyr_public
      repo-path: zephyr.git
      path: ecfwwork/zephyr_fork
      remote: zephyrproject
      revision: zephyr-v2.5.0
      clone-depth: 1
      west-commands: scripts/west-commands.yml

    - name: cmsis
      path: ecfwwork/modules/hal/cmsis
      remote: zephyrproject
      revision: c3bd2094f92d574377f7af2aec147ae181aa5f8e

    - name: hal_microchip
      path: ecfwwork/modules/hal/microchip
      remote: zephyrproject
      revision: a1ec761014740a08699720298dd37ad4da360840

  self:
    path: ecfwwork
