/*
 * Copyright (c) 2019 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief APIs for system management controller commands.
 */

#ifndef __SMCHOST_COMMANDS_H__
#define __SMCHOST_COMMANDS_H__

#define SMCHOST_READ_BYTE		0x01
#define SMCHOST_WRITE_BYTE		0x02
#define SMCHOST_ENABLE_SMI_NOTIFY	0x04
#define SMCHOST_DISABLE_SMI_NOTIFY	0x05
#define SMCHOST_QUERY_SYSTEM_STS	0x06
#define SMCHOST_GET_SMC_MODE		0x09
#define SMCHOST_GET_SWITCH_STS		0x0A
#define SMCHOST_GET_FAB_ID		0x0D
#define SMCHOST_SET_SYS_CHRG_CFG	0x12
#define SMCHOST_SET_CHRG_METHOD		0x13
#define SMCHOST_UPDATE_UVTH		0x17
#define SMCHOST_UPDATE_PWM		0x1A
#define SMCHOST_GET_PMIC_VID		0x1B
#define SMCHOST_SUSPEND_SMC		0x20
#define SMCHOST_RESUME_SMC		0x21
#define SMCHOST_SYSTEM_POWER_OFF	0x22
#define SMCHOST_ENABLE_PWR_BTN_SW	0x23
#define SMCHOST_DISABLE_PWR_BTN_SW	0x24
#define SMCHOST_ENABLE_SOFT_PWR_BTN	0x25
#define SMCHOST_DISABLE_SOFT_PWR_BTN	0x26
#define SMCHOST_SET_DSW_MODE		0x29
#define SMCHOST_GET_DSW_MODE		0x2A
#define SMCHOST_CS_ENTRY		0x2C
#define SMCHOST_CS_EXIT			0x2D
#define SMCHOST_SET_BATT_THRSLD		0x34
#define SMCHOST_GET_LEGACY_WAKE_STS	0x35
#define SMCHOST_CLEAR_LEGACY_WAKE_STS	0x36
#define SMCHOST_CHRG_RATE_CHG_NOTIFY	0x37
#define SMCHOST_PWR_BTN_SCI_CONTROL	0x38
#define SMCHOST_SET_TMP_THRESHOLD	0x4A
#define SMCHOST_SMI_QUERY		0x70
#define SMCHOST_ENABLE_PWR_BTN_NOTIFY	0x73
#define SMCHOST_DISABLE_PWR_BTN_NOTIFY	0x74
#define SMCHOST_UPDATE_SYSPWR_STATE	0x75
#define SMCHOST_READ_WAKE_STS		0x76
#define SMCHOST_CLEAR_WAKE_STS		0x77
#define SMCHOST_ACPI_READ		0x80
#define SMCHOST_ACPI_WRITE		0x81
#define SMCHOST_ACPI_BURST_MODE		0x82
#define SMCHOST_ACPI_NORMAL_MODE	0x83
#define SMCHOST_ACPI_QUERY		0x84
#define SMCHOST_GET_DOCK_STS		0x8A
#define SMCHOST_READ_REVISION		0x90
#define SMCHOST_READ_PLAT_SIGNATURE	0x92
#define SMCHOST_ENABLE_ACPI		0xAA
#define SMCHOST_DISABLE_ACPI		0xAB
#define SMCHOST_SX_ENTRY		0xAC
#define SMCHOST_SX_EXIT			0xAD
#define SMCHOST_PFAT_CMD_DISCOVERY	0xB0
#define SMCHOST_PFAT_CMD_PROV_EAV	0xB1
#define SMCHOST_PFAT_CMD_LOCK		0xB2
#define SMCHOST_PFAT_CMD_GET_SVN	0xB3
#define SMCHOST_PFAT_CMD_OPEN		0xB4
#define SMCHOST_PFAT_CMD_CLOSE		0xB5
#define SMCHOST_PFAT_CMD_PORT_TEST	0xB6
#define SMCHOST_INJECT_SMI		0xBA
#define SMCHOST_INJECT_SCI		0xBB
#define SMCHOST_DISABLE_SMI		0xBC
#define SMCHOST_ENABLE_SMI		0xBD
#define SMCHOST_UCSI_CMD_HANDLER	0xE0
#define SMCHOST_UCSI_READ_VERSION	0xE1
#define SMCHOST_READ_ACPI_SPACE		0xEA
#define SMCHOST_WRITE_ACPI_SPACE	0xEB
#define SMCHOST_GET_KSC_ID		0xEC
#define SMCHOST_BATT_SHIP_MODE		0xF2
#define SMCHOST_RESET_KSC		0xFF

#endif /* __SMCHOST_COMMANDS_H__ */

