/*
 * Copyright (c) 2019 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief APIs for system management controller commands.
 */

#ifndef __SMCHOST_COMMANDS_H__
#define __SMCHOST_COMMANDS_H__

#define SMCHOST_GET_SMC_MODE		0x09
#define SMCHOST_GET_SWITCH_STS		0x0A
#define SMCHOST_GET_PSR_SHUTDOWN_REASON 0x0C
#define SMCHOST_GET_FAB_ID		0x0D
#define SMCHOST_PLN_CONFIG		0x0F
#define SMCHOST_ENABLE_PWR_BTN_SW	0x23
#define SMCHOST_DISABLE_PWR_BTN_SW	0x24
#define SMCHOST_CS_LOW_PWR_MODE_SET	0x27
#define SMCHOST_SET_DSW_MODE		0x29
#define SMCHOST_GET_DSW_MODE		0x2A
#define SMCHOST_CS_ENTRY		0x2C
#define SMCHOST_CS_EXIT			0x2D
#define SMCHOST_PG3_SET_MODE		0x2E
#define SMCHOST_PG3_PROG_COUNTER	0x2F
#define SMCHOST_GET_LEGACY_WAKE_STS	0x35
#define SMCHOST_CLEAR_LEGACY_WAKE_STS	0x36
#define SMCHOST_HID_BTN_SCI_CONTROL	0x38
#define SMCHOST_SMI_QUERY		0x70
#define SMCHOST_ENABLE_PWR_BTN_NOTIFY	0x73
#define SMCHOST_DISABLE_PWR_BTN_NOTIFY	0x74
#define SMCHOST_ACPI_READ		0x80
#define SMCHOST_ACPI_WRITE		0x81
#define SMCHOST_ACPI_BURST_MODE		0x82
#define SMCHOST_ACPI_NORMAL_MODE	0x83
#define SMCHOST_ACPI_QUERY		0x84
#define SMCHOST_GET_DOCK_STS		0x8A
#define SMCHOST_READ_REVISION		0x90
#define SMCHOST_READ_PLAT_SIGNATURE	0x92
#define SMCHOST_ENABLE_ACPI		0xAA
#define SMCHOST_DISABLE_ACPI		0xAB
#define SMCHOST_SX_ENTRY		0xAC
#define SMCHOST_SX_EXIT			0xAD
#define SMCHOST_DISABLE_SMI		0xBC
#define SMCHOST_ENABLE_SMI		0xBD
#define SMCHOST_READ_ACPI_SPACE		0xEA
#define SMCHOST_WRITE_ACPI_SPACE	0xEB
#define SMCHOST_RESET_KSC		0xFF
#ifdef CONFIG_DEPRECATED_SMCHOST_CMD
#define SMCHOST_QUERY_SYSTEM_STS	0x06
#endif
#ifdef CONFIG_THERMAL_MANAGEMENT
#define SMCHOST_GET_HW_PERIPHERALS_STS	0x0B
#define SMCHOST_UPDATE_PWM		0x1A
#define SMCHOST_SET_OS_ACTIVE_TRIP	0x39
#define SMCHOST_SET_PECI_ACCESS_MODE	0x3C
#define SMCHOST_SET_SHDWN_THRESHOLD	0x58
#define SMCHOST_BIOS_FAN_CONTROL	0xFE
#endif
#ifdef CONFIG_DNX_EC_ASSISTED_TRIGGER_SMC
#define SMCHOST_DNX_TRIGGER		0xF6
#define SMCHOST_DNX_SET_STRAP		0xF7
#endif

#endif /* __SMCHOST_COMMANDS_H__ */

